// <auto-generated />
using Infotrack.Models.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infotrack.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210125181947_SeedSearchEngine")]
    partial class SeedSearchEngine
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Infotrack.Models.Scrape", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<int>("SearchTermId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SearchTermId");

                    b.ToTable("Scrapes");
                });

            modelBuilder.Entity("Infotrack.Models.SearchEngine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SearchEngines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Google"
                        });
                });

            modelBuilder.Entity("Infotrack.Models.SearchTerm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Keywords")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SearchEngineId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SearchEngineId");

                    b.ToTable("SearchTerms");
                });

            modelBuilder.Entity("Infotrack.Models.Scrape", b =>
                {
                    b.HasOne("Infotrack.Models.SearchTerm", "SearchTerm")
                        .WithMany("Scrapes")
                        .HasForeignKey("SearchTermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SearchTerm");
                });

            modelBuilder.Entity("Infotrack.Models.SearchTerm", b =>
                {
                    b.HasOne("Infotrack.Models.SearchEngine", "SearchEngine")
                        .WithMany("SearchTerms")
                        .HasForeignKey("SearchEngineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SearchEngine");
                });

            modelBuilder.Entity("Infotrack.Models.SearchEngine", b =>
                {
                    b.Navigation("SearchTerms");
                });

            modelBuilder.Entity("Infotrack.Models.SearchTerm", b =>
                {
                    b.Navigation("Scrapes");
                });
#pragma warning restore 612, 618
        }
    }
}
